apiVersion: v1
kind: Namespace
metadata:
  name: account-system
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: account-system
type: Opaque
data:
  MchID: dGVzdAo=
  AppID: dGVzdAo=
  MchAPIv3Key: dGVzdAo=
  MchCertificateSerialNumber: dGVzdAo=
  WechatPrivateKey: dGVzdAo=
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-system
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
  namespace: infra-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: dGVzdAo=
  AWS_SECRET_ACCESS_KEY: dGVzdAo=
  AWS_DEFAULT_REGION: dGVzdAo=
