runners:
  - name: "aws-arm64-8c16g-5"
    cloud: "aws"
    instance_type:
      - "a1.2xlarge"
    machine_image:
      - "ami-0529735c1ca82ad5f"
    region:
      - "us-east-1"
    # arm64 architecture spot instances may not be created smoothly
    preemptible: true
    labels:
      - "cirun-aws-arm64-8c-5"
