runners:
  - name: "aws-arm64-8c16g-5"
    cloud: "aws"
    instance_type:
      - "a1.2xlarge"
    machine_image:
      - "ami-078b6eb86861169a1"
    region:
      - "us-east-1"
    # arm64 architecture spot instances may not be created smoothly
    preemptible: false
    labels:
      - "cirun-aws-arm64-8c-5"
  - name: "aws-arm64-8c16g-4"
    cloud: "aws"
    instance_type:
      - "a1.2xlarge"
    machine_image:
      - "ami-03758124b4b715d9d"
    region:
      - "us-east-1"
    # arm64 architecture spot instances may not be created smoothly
    preemptible: false
    labels:
      - "cirun-aws-arm64-8c-4"