name: TestBug#2364
on:
  workflow_dispatch:
    inputs:
jobs:
  install-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trace memory
        run: |
          env
          cd /home/runner/work && tree -L 5
          free -m
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          type: install-dev
          pruneCRI: true
          sealosGit: https://github.com/dinoallo/sealos.git
          sealosGitBranch: main

      - name: Build sealos image by dockerfile
        run: |
          sudo -u root sealos build -t docker.io/testbuild:2364 --debug sealos#2346

      - name: Auto install k8s using sealos
        run: |
          sudo sealos run docker.io/testbuild:2364 --single --debug

      - name: After k8s operation
        run: |
          sleep 60
          sudo -u root crictl ps -a
          sudo -u root cat /etc/hosts
          sudo -u root systemctl status kubelet
          sudo -u root kubectl get nodes --kubeconfig /etc/kubernetes/admin.conf 
          NODENAME=$(sudo -u root kubectl get nodes -ojsonpath='{.items[0].metadata.name}' --kubeconfig /etc/kubernetes/admin.conf )
          NODEIP=$(sudo -u root kubectl get nodes -ojsonpath='{.items[0].status.addresses[0].address}' --kubeconfig /etc/kubernetes/admin.conf )
          echo "NodeName=$NODENAME,NodeIP=$NODEIP"
          sudo -u root kubectl get nodes --kubeconfig /etc/kubernetes/admin.conf 
          sudo -u root kubectl get pods -A --kubeconfig /etc/kubernetes/admin.conf 
