name: TestBug#2545
on:
  workflow_dispatch:
    inputs:
jobs:
  install-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Trace memory
        run: |
          env
          cd /home/runner/work && tree -L 5
          free -m
          local_ip=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"​`
          echo "${local_ip}"
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          type: install-dev
          sealosGit: https://github.com/cdjianghan/sealos.git
          sealosGitBranch: fixversionbug

      - name: Build sealos version
        run: |
          sudo -u root sealos version

      - name: Auto install k8s using sealos
        run: |
          sudo sealos run docker.io/labring/kubernetes:v1.24.1 --single --debug

      - name: Build sealos version
        run: |
          sudo -u root sealos version