name: TestBug#deploy
on:
  workflow_dispatch:
    inputs:
jobs:
  image-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ user, terminal, account ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: cuisongliu/sealos
          ref: 'deploy'

      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          sealosVersion: 4.1.5-alpha2


      - name: Build ${{ matrix.module }} amd64
        working-directory: controllers/${{ matrix.module }}
        run: |
          GOARCH=amd64 make build
          mv bin/manager bin/controller-${{ matrix.module }}-amd64
          chmod +x bin/controller-${{ matrix.module }}-amd64

      - name: Prepare
        id: prepare
        run: |
          TAG=deploy
          echo tag_name=${TAG} >> $GITHUB_OUTPUT

      - name: build   ${{ matrix.module }} main controller image
        env:
          # fork friendly ^^
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/sealos-${{ matrix.module }}-controller
        working-directory: controllers/${{ matrix.module }}/deploy
        run: |
          ls -l
          sealos build --debug  -t ${DOCKER_REPO}:${{ steps.prepare.outputs.tag_name }}-cluster .
          sealos login -u ${{ github.repository_owner }} -p ${{ secrets.G_REGISTRY_TOKEN }} --debug ghcr.io
          sealos push  ${DOCKER_REPO}:${{ steps.prepare.outputs.tag_name }}-cluster
      - name: docker images
        run: |
          sudo sealos images
  verify:
    needs:
      - image-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          sealosVersion: 4.1.5-alpha2

      - name: Auto install k8s using sealos
        run: |
          sudo sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 labring/cert-manager:v1.8.0 --single --debug
          mkdir -p "$HOME/.kube"
          sudo cp -i /etc/kubernetes/admin.conf "$HOME/.kube/config"
          sudo chown "$(whoami)" "$HOME/.kube/config"
          kubectl get nodes --no-headers -oname | while read -r node; do kubectl get "$node" -o template='{{range .spec.taints}}{{.key}}{{"\n"}}{{end}}' | while read -r taint; do
            kubectl taint ${node/\// } "$taint"-
          done; done
          kubectl get pods -owide --all-namespaces
          kubectl get node -owide
          sleep 9
          date
          until ! kubectl get pods --no-headers --all-namespaces | grep -vE Running; do
            sleep 5
            echo
            kubectl get pods -owide --all-namespaces | grep -vE Running
            if kubectl get pods --no-headers --all-namespaces | grep -E "30m.+s"; then
              break
            fi
          done
          date
          kubectl get pods -owide --all-namespaces
          kubectl get node -owide
      - name: Prepare
        id: prepare
        run: |
          TAG=deploy
          echo tag_name=${TAG} >> $GITHUB_OUTPUT
      - name: Auto install app using sealos
        run: |
          sudo sealos run ghcr.io/${{ github.repository_owner }}/sealos-user-controller:${{ steps.prepare.outputs.tag_name }}-cluster
      - name: Auto install app using sealos
        working-directory: sealos#deploy
        run: |
          kubectl apply -f deploy.yaml
          sudo sealos run ghcr.io/${{ github.repository_owner }}/sealos-account-controller:${{ steps.prepare.outputs.tag_name }}-cluster

      - name: Auto install app using sealos
        run: |
          sudo sealos run ghcr.io/${{ github.repository_owner }}/sealos-terminal-controller:${{ steps.prepare.outputs.tag_name }}-cluster

      - name: After k8s operation
        run: |
          sleep 60
          sudo -u root crictl ps -a
          sudo -u root cat /etc/hosts
          sudo -u root systemctl status kubelet
          sudo -u root kubectl get nodes --kubeconfig /etc/kubernetes/admin.conf 
          NODENAME=$(sudo -u root kubectl get nodes -ojsonpath='{.items[0].metadata.name}' --kubeconfig /etc/kubernetes/admin.conf )
          NODEIP=$(sudo -u root kubectl get nodes -ojsonpath='{.items[0].status.addresses[0].address}' --kubeconfig /etc/kubernetes/admin.conf )
          echo "NodeName=$NODENAME,NodeIP=$NODEIP"
          sudo -u root kubectl get nodes --kubeconfig /etc/kubernetes/admin.conf 
          sudo -u root kubectl get pods -A --kubeconfig /etc/kubernetes/admin.conf
