# This is a basic workflow to help you get started with Actions

name: TestBug#images

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:

jobs:
  sealos-containerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          type: install
          sealosVersion: 4.2.2

      - name: Install sealos version
        run: |
          sudo sealos version  
          sudo sealctl version 
          sudo buildah version


      - name: Build sealos image by kubefile
        working-directory: sealos#build/build-kubefile
        run: |
          sudo sealos run labring/kubernetes:v1.25.0 labring/calico:v3.24.1 labring/openebs:v3.4.0 --debug
          sudo wget https://github.com/apecloud/kubeblocks/releases/download/v0.5.2/kbcli-linux-amd64-v0.5.2.tar.gz
          sudo tar -zxvf kbcli-linux-amd64-v0.5.2.tar.gz
          sudo mv linux-amd64/kbcli /usr/local/bin/
          sudo kbcli version
          sudo kbcli kubeblocks install --monitor=false
          sudo kbcli kubeblocks status
