# This is a basic workflow to help you get started with Actions

name: TestBug#images

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:

jobs:
  sealos-containerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune
      - name: Build sealos image by kubefile
        run: |
          sudo wget https://github.com/labring/sealos/releases/download/v4.2.2/sealos_4.2.2_linux_amd64.tar.gz
          sudo tar -zxvf sealos_4.2.2_linux_amd64.tar.gz sealos
          sudo chmod +x sealos
          sudo mv sealos /usr/local/bin/
      - name: Install sealos version
        run: |
          sudo sealos version  

      - name: Build sealos image by kubefile
        run: |
          sudo sealos run labring/kubernetes:v1.25.0 labring/calico:v3.24.1 labring/openebs:v3.4.0 --debug
          sudo wget https://github.com/apecloud/kubeblocks/releases/download/v0.5.2/kbcli-linux-amd64-v0.5.2.tar.gz
          sudo tar -zxvf kbcli-linux-amd64-v0.5.2.tar.gz
          sudo mv linux-amd64/kbcli /usr/local/bin/
          sudo kbcli version
#          sudo kbcli kubeblocks install --monitor=false --set snapshot-controller.enabled=false
          sudo kbcli kubeblocks install
          sudo kbcli kubeblocks status
          sudo kbcli cluster create pg-cluster --cluster-definition=postgresql --set cpu=2,memory=2Gi,replicas=2,storage=20Gi --namespace kb-system
          sudo kbcli cluster create mongodb-cluster  --cluster-definition=mongodb   --set cpu=1,memory=1Gi,storage=10Gi --namespace kb-system
          sudo kbcli cluster create redis-cluster  --cluster-definition=redis   --set type=redis,cpu=1,memory=1Gi,replicas=2,storage=10Gi --set type=redis-sentinel,cpu=1,memory=1Gi,replicas=3,storage=1Gi --namespace kb-system
          sudo kbcli cluster create mysql-cluster --cluster-definition=apecloud-mysql --set cpu=2000m,memory=2Gi,storage=20Gi --namespace kb-system
          sudo kbcli cluster describe pg-cluster
          sudo kbcli cluster describe mongodb-cluster
          sudo kbcli cluster describe redis-cluster
          sudo kbcli cluster describe mysql-cluster
          sudo kubectl get node
          sudo kubectl get pod -A
          sudo kubectl get pod -n kb-system -o yaml | grep "image:" | sed 's/- /  /g' | awk '{print $2}' | sort | uniq
