# This is a basic workflow to help you get started with Actions

name: TestBug#run1.25.0

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:

jobs:
  sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.4
        with:
          type: install
          sealosVersion: 4.2.0
      - name: Remove containerd && docker
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune

      - name: Install sealos version
        run: |
          sudo sealos version  
          sudo sealctl version 
          sudo buildah version


      - name: Build sealos image by kubefile
        working-directory: sealos#build/build-kubefile
        run: |
          sudo sealos run --debug  docker.io/labring/kubernetes:v1.25.0
