# This is a basic workflow to help you get started with Actions

name: TestBug#run1.25.0

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:

jobs:
  sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Remove containerd && docker
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune

      - name: Install sealos version
        run: |
          sudo sealos version  
          sudo sealctl version 
          sudo buildah version


      - name: Build sealos image by kubefile
        working-directory: sealos#build/build-kubefile
        run: |
          wget https://github.com/labring/sealos/releases/download/v4.2.0/sealos_4.2.0_linux_amd64.tar.gz
          tar -zxvf sealos_4.2.0_linux_amd64.tar.gz sealos
          chmod +x sealos
          sudo mv sealos /usr/local/bin/
          sudo sealos run --debug  docker.io/labring/kubernetes:v1.25.0
          mkdir -p "$HOME/.kube"
          sudo cp -i /etc/kubernetes/admin.conf "$HOME/.kube/config"
          sudo chown "$(whoami)" "$HOME/.kube/config"
          sudo kubectl get node
