# This is a basic workflow to help you get started with Actions

name: TestBug#tag-aliyun

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:

jobs:
  sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Remove containerd && docker
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune

      - name: Build sealos image by kubefile
        run: |
          wget https://github.com/labring/sealos/releases/download/v4.2.0/sealos_4.2.0_linux_amd64.tar.gz
          tar -zxvf sealos_4.2.0_linux_amd64.tar.gz sealos
          chmod +x sealos
          sudo mv sealos /usr/local/bin/
          sudo sealos version
          sudo sealos pull labring/kubernetes:v1.23.9
          sudo sealos tag labring/kubernetes:v1.23.9 registry.cn-hongkong.aliyuncs.com/cuisongliu-labring/kubernetes-aa:v1.23.9
          sudo sealos login -u cuisongliu@1186388767322904 -p ${{ secrets.A_REGISTRY_TOKEN }}  registry.cn-hongkong.aliyuncs.com
          date
          sudo sealos push registry.cn-hongkong.aliyuncs.com/cuisongliu-labring/kubernetes-aa:v1.23.9
          date
